---
format:
  revealjs: default
metadata-files:
  - ../_diapos.yml
---

## Lectures recommandées

Ce chapitre est adapté du chapitre 8 du texte _Basic Ratemaking_ :

[Werner, G. et Modlin, C. (2016). _Basic Ratemaking_, Casualty Actuarial Society, 5e édition.](http://www.casact.org/library/studynotes/Werner_Modlin_Ratemaking.pdf)

## Contenu du chapitre {.progress-overview}

- Indiqué de niveau de taux global
- Méthode de la prime pure
- Méthode du taux de sinistre
- Comparaison des méthodes

::: {.aside}
Adapté de : Werner, G. et Modlin, C. (2016), _Basic Ratemaking_, Casualty Actuarial Society.
:::

# Indiqué de niveau de taux global {data-progress-label="Indiqué global"}

## Indiqué de niveau de taux global {.english-subtitle subtitle="Overall Indication"}

Équation fondamentale en assurance :

$$
\begin{aligned}
\text{Prime} ={}& \text{Sinistres} \\
&+ \text{Frais de règlement de sinistres} \\
&+ \text{Frais de souscription} \\
&+ \text{Profit de souscription}
\end{aligned}
$$

---


Les chapitres précédents ont fourni des techniques pour ajuster les données historiques afin d’estimer les différentes composantes de l’équation fondamentale en assurance pour la période future où les taux seront en vigueur.

Le chapitre 8 démontre comment combiner les différentes composantes estimées pour vérifier si les taux actuels sont appropriés au niveau global. Les chapitres suivants couvrent les indiqués par sous-classes d’assurés.

## Indiqué de niveau de taux global

Deux approches mathématiquement équivalentes pour déterminer le niveau de taux global :

1. Méthode de la prime pure
1. Méthode du taux de sinistre

# Méthode de la prime pure {data-progress-label="Prime pure" subtitle="Projeter les coûts et les frais fixes par unité d'exposition"}

## Méthode de la prime pure {.english-subtitle subtitle="Pure Premium Method"}

- Méthode la plus simple et la plus directe.
- Détermine une **prime moyenne indiquée**.
- Projection des sinistres, des frais de règlement de sinistres et des frais de souscription fixes par unité pour la période où les taux seront en vigueur. Cette projection est ajustée pour les frais variables et le profit de souscription cible.

---

::: {.text-xs}
$$
\begin{align}
&\text{Prime moyenne indiquée par unité} = \\ \\
 &\frac{
  \text{Prime pure (incluant frais de règl. de sinistres)}
  + \text{Frais de souscription fixes par unité}
}{1 - \% \text{Frais variables} - \% \text{Profit de souscription cible}}
\end{align}
$$
:::

---

$$
\begin{aligned}
\overline{P_I}
&= \frac{\overline{L} + \overline{E_L} + \overline{E_F}}{1 - V - Q_T} \\
&= \frac{\left[(L + E_L) / X\right] + E_F / X}{1 - V - Q_T}
\end{aligned}
$$

:::: {.columns .text-xs}
::: {.column width="40%"}
- $X$ : Unités d’exposition
- $L$ : Sinistres
- $E_L$ : Frais de règlement de sinistres
- $E_F$ : Frais de souscription fixes
- **$V$** : Provision pour frais variables
:::

::: {.column width="60%"}
- $\overline{P_I}$ : Prime indiquée moyenne
- $\overline{L} = L / X$ = Prime pure
- $\overline{E_L} = E_L / X$ = Frais de règlement moyens par unité
- $\overline{E_F} = E_F / X$ = Frais fixes par unité

- **$Q_T$** : Profit de souscription cible
:::
::::

## Nouvelle compagnie

Lorsqu’un actuaire essaie de déterminer les taux pour une nouvelle compagnie, il n’y aura pas de données internes historiques.

Dans ces cas, l’actuaire peut tout de même déterminer le taux indiqué en estimant la prime pure espérée et les provisions pour frais, puis en sélectionnant une provision pour profit cible. Il peut se baser soit sur des données externes, soit faire des sélections au jugement.

:::: {.question title="Prime moyenne indiquée"}

##

Avec les données suivantes :

- Prime pure projetée incluant les frais de règlement de sinistres : 300 $
- Frais de souscription fixes projetés par unité : 25 $
- Frais variables : 25 % de la prime
- Profit de souscription cible : 10 %

Calculer la prime moyenne indiquée par unité.

::: {.solution}

##

$$
\overline{P_I}
= \frac{300 + 25}{1 - 0.25 - 0.10}
= \frac{325}{0.65}
= 500\ \text{\$}
$$

La prime moyenne indiquée par unité est donc de **500 $**.

:::

::::

# Méthode du taux de sinistre {data-progress-label="Taux de sinistre" subtitle="Comparer les coûts projetés aux primes au taux courant"}

## Méthode du taux de sinistre {.english-subtitle subtitle="Loss Ratio Method"}

- Méthode la plus fréquemment utilisée.
- Compare le pourcentage de chaque dollar de prime nécessaire pour couvrir les sinistres futurs, les frais de règlement de sinistres et autres frais fixes au pourcentage de chaque dollar qui est disponible pour payer ces coûts.

## Méthode du taux de sinistre {.text-smaller}

Facteur de changement de taux indiqué :

$$
\begin{aligned}
&\text{Facteur de changement de taux indiqué} = \\ \\
&\frac{
  \text{Taux de sinistres et frais de règl. de sinistres} + \text{Ratio de frais fixes}
}{
  1 - \% \text{Frais variables} - \% \text{Profit de souscription cible}
} \\
&= \frac{\left[(L + E_L) / P_c\right] + F}{1 - V - Q_T} \\ \\
&\text{Changement indiqué}
= \frac{\left[(L + E_L) / P_c\right] + F}{1 - V - Q_T} - 1
\end{aligned}
$$

Où $P_c$ est la prime au taux courant et $F$ est le ratio de frais fixes.

:::: {.question title="Changement indiqué"}

##

Avec les données suivantes :

- Taux de sinistre et frais de règlement de sinistres projeté : 0.65
- Ratio frais fixes projetés : 0.065
- Ratio frais variables : 0.25
- Profit de souscription cible : 10 %

Calculer le changement indiqué.

::: {.solution}

##

$$
\begin{aligned}
\text{Changement indiqué}
&= \frac{\left[(L + E_L) / P_c\right] + F}{1 - V - Q_T} - 1 \\
&= \frac{0.65 + 0.065}{1 - 0.25 - 0.10} - 1 \\
&= \frac{0.715}{0.65} - 1 \\
&= +10\%
\end{aligned}
$$

Le changement indiqué est donc de **10 %**.

:::

::::

# Comparaison des méthodes {data-progress-label="Comparaison"}

## Comparaison des approches

Deux différences majeures entre les deux approches :

1. Mesure de perte sous-jacente utilisée
    - La méthode du taux de sinistre se base sur le **taux de sinistre** :  
    $$
    \frac{\text{sinistres ultimes projetés et frais de règlement}}{\text{prime projetée au taux courant}}
    $$

    - La méthode de la prime pure se base sur la **statistique de prime pure** :  
    $$
    \frac{\text{sinistres ultimes projetés et frais de règlement}}{\text{unités projetées}}
    $$

    - Cela signifie que la méthode du taux de sinistre requiert les primes au taux courant alors que la méthode de la prime pure n’en a pas besoin. La méthode de la prime pure a besoin quant à elle d’unités d’exposition bien définies.

---

2. Nature du résultat obtenu
    - La méthode du taux de sinistre donne un **changement indiqué** par rapport aux taux courants.
    - La méthode de la prime pure donne un **taux indiqué**.
    - Cela signifie que la méthode de la prime pure doit être utilisée pour une nouvelle ligne d’affaires pour laquelle il n’y a pas de taux courant à ajuster.

:::: {.question title="Provision pour profit"}

## {.text-smaller}

Exemple adapté de la question 7 de l’examen 5, automne 2016 de la CAS.

Un employé d’un organisme de réglementation gouvernementale veut comparer les provisions pour profit entre compagnies.

:::: {.columns}

::: {.column width="50%"}
**Compagnie A**

| Hypothèse | Valeur |
|:--|--:|
| Frais fixes projetés | 50 000 $ |
| Sinistres et frais de règlement projetés | 600 000 $ |
| Unités projetées | 2 000 |
| Taux indiqué par unité | 500 $ |
:::

::: {.column width="50%"}
**Compagnie B**

| Hypothèse | Valeur |
|:--|--:|
| Frais fixes projetés | 50 000 $ |
| Sinistres et frais de règlement projetés | 600 000 $ |
| Primes projetées au taux courant | 900 000 $ |
| Changement de taux indiqué | 16.5 % |
:::

::::

## {.text-smaller}

Le ratio de frais variables est le même pour les deux compagnies.

1. Déterminer quel dépôt de manuel de taux contient la plus grande provision pour profit.
1. Donner deux raisons pour lesquelles la provision pour profit peut différer entre deux compagnies avec la même expérience de sinistres, frais de règlement et dépenses.

::: {.solution}

## {.text-smaller}

Pour la compagnie A, on utilise la méthode de la prime pure :

$$
500\ \text{\$} = \frac{600\,000 / 2\,000 + 50\,000 / 2\,000}{1 - V - Q_A}
= \frac{325}{1 - V - Q_A}
$$

Donc : $1 - V - Q_A = 0.65$

Pour la compagnie B, on utilise la méthode du taux de sinistre :

$$
1.165 = \frac{600\,000 / 900\,000 + 50\,000 / 900\,000}{1 - V - Q_B}
= \frac{0.7222}{1 - V - Q_B}
$$

Donc : $1 - V - Q_B = 0.6199$

Comme le ratio de frais variables est le même pour les deux compagnies ($V_A = V_B$), la **compagnie B** contient la plus grande provision pour profit ($Q_B > Q_A$).

##

*Donner deux raisons pour lesquelles la provision pour profit peut différer entre deux compagnies avec la même expérience de sinistres, frais de règlement et dépenses.*

Deux raisons possibles :

- Une compagnie peut choisir de diminuer sa marge de profit pour être plus compétitive et augmenter sa part de marché
- Une compagnie peut faire davantage de profit d’investissement et pouvoir se permettre un plus petit profit de souscription tout en atteignant le même profit total

:::

::::

## {.remember-slide}

L’indiqué global compare les primes requises aux primes au taux courant. Deux méthodes :

- **Prime pure** : exprime les coûts par unité.

$$
\begin{aligned}
\overline{P_I}
&= \frac{\overline{L} + \overline{E_L} + \overline{E_F}}{1 - V - Q_T}
\end{aligned}
$$
    
- **Taux de sinistre** : exprime les coûts en pourcentage des primes.

$$
\begin{aligned}
&\text{Changement indiqué}
= \frac{\left[(L + E_L) / P_c\right] + F}{1 - V - Q_T} - 1
\end{aligned}
$$
