---
metadata-files:
  - ../_exercices.yml
---

:::: {.question}
(CAS Examen 5, 2004 – Q30)

::: {.question}
Donnez trois caractéristiques désirables d’une base d’exposition.

::: {.solution}
- Varie proportionnellement avec les sinistres espérés
- Pratique (c.-à-d. objective et relativement facile et peu coûteuse à obtenir et vérifier)
- Considérer les bases d’exposition historiques, car il est coûteux de changer de base d’exposition.
:::
:::

::: {.question}
Pour chacune des lignes d’affaires présentées, donnez une base d’exposition raisonnable et discutez d’un des critères donnés en a. :

1. *Workers Compensation* (c.-à-d. similaire à la CSST au Québec)
2. Assurance bateau

::: {.solution}
1. Salaire

   Pratique, car il est disponible sur les formulaires d’impôts des entreprises.

2. Bateau-année

   Varie proportionnellement avec les sinistres espérés. Deux bateaux devraient avoir deux fois plus de sinistres espérés qu’un bateau.
:::
:::
::::

::: {.question}
(CAS Examen 5, 2005 – Q14) Une police annuelle couvrant 2 véhicules a été écrite le 1er mai 2004. Une deuxième police annuelle couvrant un véhicule a été écrite le 1er novembre 2004. Lequel des choix suivants représente les unités d’exposition vues au 31 décembre 2004 :

| Choix | Unités écrites de l’année de calendrier 2004 | Unités acquises de l’année de calendrier 2004 | Unités en force |
|---|---:|---:|---:|
| A. | 3.0 | 1.5 | 1.5 |
| B. | 3.0 | 1.5 | 3.0 |
| C. | 3.0 | 3.0 | 3.0 |
| D. | 6.0 | 1.5 | 3.0 |
| E. | 6.0 | 3.0 | 3.0 |

::: {.solution}
- Les deux véhicules de la police écrite le 1er mai 2004 comptent pour deux unités écrites et le véhicule de la police écrite le 1er novembre 2004 compte pour une unité écrite. Le total d’unités écrites pour l’année de calendrier 2004 est donc 3.
- Les deux véhicules de la police écrite le 1er mai 2004 comptent pour $2 \times 8/12$ unités acquises. Le véhicule de la police écrite le 1er novembre 2004 compte pour 2/12 unités acquises. Le total d’unités acquises pour l’année de calendrier 2004 est donc 1.5.
- Les deux véhicules de la police écrite le 1er mai 2004 sont en force au 31 décembre 2004 et comptent donc pour 2 unités en force. Le véhicule de la police écrite le 1er novembre 2004 est en force au 31 décembre 2004 et compte donc pour 1 unité en force. Le total des unités en force vu au 31 décembre 2004 est donc 3.

Réponse : B
:::
:::

:::: {.question}
(CAS Examen 5, 2008 – Q12) Une compagnie d’assurance veut vendre de l’assurance contre le vol d’identité en lien avec l’usage non autorisé de cartes de crédit et doit sélectionner une base d’exposition.

::: {.question}
Identifiez et décrivez brièvement trois caractéristiques désirables d’une base d’exposition.

::: {.solution}
- Une base d’exposition devrait varier proportionnellement avec les sinistres espérés. Une police avec deux unités d’exposition devrait présenter deux fois plus de sinistres espérés qu’une police similaire avec une seule unité d’exposition.
- Pratique. Une base d’exposition devrait être objective et relativement facile et peu coûteuse à obtenir et vérifier.
- Une base d’exposition devrait considérer les bases d’exposition historiques, car il est coûteux de changer de base d’exposition.
:::
:::

::: {.question}
Identifiez une base d’exposition possible contre le vol d’identité et évaluez cette base d’exposition à l’aide des trois critères identifiés en a.

::: {.solution}
Une base d’exposition raisonnable serait le nombre de cartes de crédit.

- Proportionnelle aux sinistres espérés, car le fait d’avoir plus de cartes de crédit signifie généralement plus d’opportunités de vol d’identité.
- Pratique (vérifiable avec les fournisseurs de données de crédit)
- Le critère de bases d’exposition historiques ne s’applique pas dans ce cas-ci, car l’assurance contre le vol d’identité est nouvelle et n’a jamais été offerte par cette compagnie.
:::
:::
::::

:::: {.question}
(CAS Examen 5, 2010 – Q16)

::: {.question}
Identifiez et décrivez brièvement deux critères d’une bonne base d’exposition.

::: {.solution}
Voir 3a.
:::
:::

::: {.question}
Évaluez la « valeur marchande d’une maison » selon les deux critères identifiés en a.

::: {.solution}
- Cette base d’exposition n’est pas proportionnelle aux sinistres espérés. Une maison de 400 000 \$ n’a pas deux fois plus de sinistres espérés qu’une maison de 200 000 \$.
- Cette base d’exposition n’est pas pratique, car elle est subjective.
- La base d’exposition historique pour l’assurance habitation est normalement une maison-année. La valeur marchande serait donc un changement de base d’exposition et serait coûteux à implanter.
:::
:::

::: {.question}
Donnez deux raisons pour lesquelles le fait de changer de base d’exposition peut être difficile.

::: {.solution}
- Peut donner des changements de primes importants pour les assurés
- Nécessite des changements à l’algorithme de tarification
- Peut nécessiter des ajustements aux données pour analyses futures.
:::
:::
::::

:::: {.question}
(CAS Examen 5, 2010 – Q17)

Avec les activités suivantes sur cinq polices annuelles en assurance automobile au 30 juin 2009 :

| Police | Date effective | Date d’expiration originale | Date de l’annulation en cours de terme |
|---|---|---|---|
| 1 | 1er juillet 2007 | 30 juin 2008 | N/A |
| 2 | 1er octobre 2007 | 30 septembre 2008 | 31 mars 2008 |
| 3 | 1er janvier 2008 | 31 décembre 2008 | N/A |
| 4 | 1er mars 2008 | 28 février 2009 | 30 juin 2008 |
| 5 | 1er juillet 2008 | 30 juin 2009 | N/A |

La base d’exposition est un véhicule-année.

::: {.question}
Calculez les unités écrites pour l’année de calendrier 2008.

::: {.solution}
| Police | Unités écrites Année de calendrier 2008 |
|---|---:|
| 1 | 0 |
| 2 | 0 - 6/12 |
| 3 | 1 |
| 4 | 1 - 8/12 |
| 5 | 1 |
| **Total** | **1.833** |

1.833
:::
:::

::: {.question}
Calculez les unités acquises pour l’année de calendrier 2008.

::: {.solution}
| Police | Unités acquises Année de calendrier 2008 |
|---|---:|
| 1 | 6/12 |
| 2 | 9/12 - 6/12 |
| 3 | 12/12 |
| 4 | 10/12 - 6/12 |
| 5 | 6/12 |
| **Total** | **2.583** |

2.583
:::
:::

::: {.question}
Calculez les unités écrites pour l’année de police 2007.

::: {.solution}
| Police | Unités écrites Année de police 2007 |
|---|---:|
| 1 | 1 |
| 2 | 1 - 6/12 |
| 3 | 0 |
| 4 | 0 |
| 5 | 0 |
| **Total** | **1.5** |

1.5
:::
:::

::: {.question}
Calculez les unités en force au 1er avril 2008.

::: {.solution}
| Police | Unités en force au 1er avril 2008 |
|---|---:|
| 1 | 1 |
| 2 | 0 |
| 3 | 1 |
| 4 | 1 |
| 5 | 0 |
| **Total** | **3** |

3
:::
:::
::::

:::: {.question}
(CAS Examen 5, 2011 – Q3)

Avec les données suivantes :

- Chaque police assure seulement un véhicule.
- Les polices sont acquises uniformément dans l’année.

| Police | Date effective | Date d’expiration originale | Date de l’annulation en cours de terme |
|---|---|---|---|
| A | 1er février 2009 | 31 juillet 2009 |  |
| B | 1er mai 2009 | 31 octobre 2009 |  |
| C | 1er août 2009 | 31 janvier 2010 |  |
| D | 1er novembre 2009 | 30 avril 2010 | 31 janvier 2010 |
| E | 1er janvier 2010 | 30 juin 2010 |  |
| F | 1er juillet 2010 | 31 décembre 2010 |  |

::: {.question}
Calculez le nombre de véhicule-année écrit dans l’année de calendrier 2010.

::: {.solution}
| Police | Véhicule-année écrit Année de calendrier 2010 |
|---|---:|
| A | 0 |
| B | 0 |
| C | 0 |
| D | -3/12 |
| E | 6/12 |
| F | 6/12 |
| **Total** | **0.75** |

0.75
:::
:::

::: {.question}
Calculez le nombre de véhicule-année écrit dans l’année de police 2010.

::: {.solution}
| Police | Véhicule-année écrit Année de police 2010 |
|---|---:|
| A | 0 |
| B | 0 |
| C | 0 |
| D | 0 |
| E | 6/12 |
| F | 6/12 |
| **Total** | **1** |

1
:::
:::

::: {.question}
Calculez le nombre de véhicule-année acquis dans l’année de calendrier 2010.

::: {.solution}
| Police | Véhicule-année acquis Année de calendrier 2010 |
|---|---:|
| A | 0 |
| B | 0 |
| C | 1/12 |
| D | 4/12 - 3/12 |
| E | 6/12 |
| F | 6/12 |
| **Total** | **1.167** |

1.167
:::
:::

::: {.question}
Calculez le nombre de véhicule-année acquis dans l’année de police 2010.

::: {.solution}
| Police | Véhicule-année acquis Année de police 2010 |
|---|---:|
| A | 0 |
| B | 0 |
| C | 0 |
| D | 0 |
| E | 6/12 |
| F | 6/12 |
| **Total** | **1** |

1
:::
:::

::: {.question}
Calculez le nombre de polices en force au 1er janvier 2010.

::: {.solution}
| Police | Police en force au 1er janvier 2010 |
|---|---:|
| A | 0 |
| B | 0 |
| C | 1 |
| D | 1 |
| E | 1 |
| F | 0 |
| **Total** | **3** |

3
:::
:::
::::

:::: {.question}
(CAS Examen 5, 2012 – Q3)

Avec les données suivantes :

- Une compagnie d’assurance a commencé à écrire des polices le 1er janvier 2011.
- Les polices ont des termes annuels.

| Dates effectives de police | Nombre d’unités |
|---|---:|
| 1er janvier au 31 mars | 100 |
| 1er avril au 30 juin | 200 |
| 1er juillet au 30 septembre | 300 |
| 1er octobre au 31 décembre | 400 |

::: {.question}
Calculez les unités acquises en 2011 en supposant que les polices sont écrites uniformément dans chaque trimestre.

::: {.solution}
| Trimestre | Date d’effet supposée | Unités acquises dans l’année de calendrier 2011 |
|---|---|---:|
| 1er janvier au 31 mars | 15 février | $100 \times 21/24 = 87.5$ |
| 1er avril au 30 juin | 15 mai | $200 \times 15/24 = 125$ |
| 1er juillet au 30 septembre | 15 août | $300 \times 9/24 = 112.50$ |
| 1er octobre au 31 décembre | 15 novembre | $400 \times 3/24 = 50$ |
| **Total** |  | **375** |
:::
:::

::: {.question}
Discutez de la justesse de l’hypothèse en a. étant donné les données fournies.

::: {.solution}
L’hypothèse que les unités sont écrites uniformément dans le trimestre semble inappropriée étant donné qu’il y a une hausse importante des unités écrites d’un trimestre à l’autre. Sachant cela, il est plus probable que les unités augmentent durant un même trimestre.
:::
:::
::::

:::: {.question}
(CAS Examen 5, Printemps 2013 – Q1)

Avec les données suivantes pour une compagnie d’assurance qui écrit des polices avec des termes de 24 mois :

| Groupe de polices | Date effective | Date d’expiration | Nombre de véhicules |
|---|---|---|---:|
| A | 1er janvier 2010 | 31 décembre 2011 | 50 |
| B | 1er juillet 2010 | 30 juin 2012 | 100 |

::: {.question}
Calculez le nombre de véhicule-année acquis pour l’année de calendrier 2011.

::: {.solution}
$\text{Véhicule-années acquises en 2011} = 50 \times \frac{12}{12} + 100 \times \frac{12}{12} = 150$

ou $\text{Véhicule-années acquises en 2011} = 50 \times 2 \times \frac{1}{2} + 100 \times 2 \times \frac{1}{2} = 150$
:::
:::

::: {.question}
Calculez le nombre de véhicule-année acquis pour l’année de police 2010, évalué au 31 décembre 2010 et au 31 décembre 2011.

::: {.solution}
$\text{Au 31 décembre 2010} = 50 \times \frac{12}{12} + 100 \times \frac{6}{12} = 100$

$\text{Au 31 décembre 2011} = 50 \times \frac{24}{12} + 100 \times \frac{18}{12} = 250$

ou

$\text{Au 31 décembre 2010} = 50 \times 2 \times 0.5 + 100 \times 2 \times \frac{1}{4} = 100$

$\text{Au 31 décembre 2011} = 50 \times 2 + 100 \times 2 \times \frac{3}{4} = 250$
:::
:::

::: {.question}
Supposez que le groupe de polices B annule le 1er janvier 2011. Calculez le nombre de véhicule-année écrit pour l’année de police 2010, évalué au 31 décembre 2010 et au 31 décembre 2011 pour le groupe de polices B.

::: {.solution}
$\text{Au 31 décembre 2010} = 100 \times \frac{24}{12} = 200$

$\text{Au 31 décembre 2011} = 100 \times \frac{24}{12} - 100 \times \frac{18}{12} = 50$

ou

$\text{Au 31 décembre 2010} = 100 \times 2 = 200$

$\text{Au 31 décembre 2011} = 100 \times 2 - 100 \times 2 \times \frac{3}{4} = 50$
:::
:::

::: {.question}
Supposez que le groupe de polices B annule le 1er juillet 2011. Calculez le nombre de véhicule-année écrit pour l’année de calendrier 2010 et pour l’année de calendrier 2011 pour le groupe de polices B.

::: {.solution}
$\text{Année de calendrier 2010} = 100 \times \frac{24}{12} = 200$

$\text{Année de calendrier 2011} = -100 \times \frac{12}{12} = -100$

ou

$\text{Année de calendrier 2010} = 100 \times 2 = 200$

$\text{Année de calendrier 2011} = -100 \times 2 \times 0.5 = -100$
:::
:::
::::

:::: {.question}
(CAS Examen 5, Automne 2015 – Q2)

::: {.question}
À partir de deux critères pertinents, proposez et justifiez brièvement une base d’exposition appropriée pour la responsabilité civile d’un restaurant.

::: {.solution}
Plusieurs mentions dans le chapitre 4 sur les bases d’exposition possibles en assurance responsabilité civile des entreprises : recettes, salaires, superficie, nombre d’unités. Pour un restaurant, les recettes et le salaire pourraient être deux options valables. Comme les recettes sont habituellement utilisées pour l’assurance responsabilité des restaurants, ce serait le choix privilégié :

- Base d’exposition proportionnelle aux sinistres espérés, car plus de ventes veut généralement dire plus de clients qui peuvent subir un dommage.
- Pratique : les ventes sont une base d’exposition objective et facile à obtenir et vérifier dans les rapports financiers du restaurant.
- Bases d’exposition historiques : les recettes sont généralement utilisées pour l’assurance responsabilité des restaurants, donc il est moins coûteux de conserver cette base (pas de dislocation des primes pour l’assuré, pas de coûts de changement de l’algorithme de tarification).
:::
:::

::: {.question}
À partir de deux critères pertinents, proposez et justifiez brièvement une base d’exposition appropriée pour la responsabilité professionnelle d’un hôpital.

::: {.solution}
Nombre de professionnels-année

- Base proportionnelle aux sinistres espérés, car plus de médecins/infirmières veut dire plus de patients vus dans l’année et donc plus de réclamations potentielles.
- Pratique : un hôpital connaît normalement son nombre d’employés, donc ce nombre devrait être objectif et facile à vérifier auprès de l’hôpital.
:::
:::
::::

::: {.question}
(CAS Examen 5, Printemps 2016 – Q2d) Une compagnie d’assurance automobile écrit des polices 6 mois et des polices 12 mois. Avec l’information suivante :

| Police | Date d’effet de la police | Date d’expiration de la police | Date effective de la transaction | Territoire | Prime écrite du terme | Note |
|---|---|---|---|---:|---:|---|
| A | 1er janvier 2015 | 31 décembre 2015 | 1er janvier 2015 | 1 | 1000 | Début de la police |
| A | 1er janvier 2015 | 31 décembre 2015 | 1er juillet 2015 | 1 | NA | Police annulée |
| B | 1er juillet 2015 | 30 juin 2016 | 1er juillet 2015 | 1 | 500 | Début de la police |
| B | 1er juillet 2015 | 30 juin 2016 | 30 septembre 2015 | 2 | 400 | Relocalisation dans le territoire 2 |
| C | 1er octobre 2015 | 31 mars 2016 | 1er octobre 2015 | 2 | 1000 | Début de la police |

Calculez les unités acquises pour l’année de calendrier 2015 séparément pour les territoires 1 et 2, évaluées au 31 décembre 2015.

::: {.solution}
Territoire 1

- Police A : du 1er janvier 2015 au 1er juillet 2015 : $6/12 = 0.5$
- Police B : du 1er juillet 2015 au 29 septembre 2015 : $3/12 = 0.25$
- Police C : aucune exposition dans le territoire 1 : $0$

Total territoire 1 : $0.75$

Territoire 2

- Police A : aucune exposition dans le territoire 2 : $0$
- Police B : du 30 septembre 2015 au 31 décembre 2015 : $3/12 = 0.25$
- Police C : du 1er octobre 2015 au 31 décembre 2015 : $3/12$ (ou $0.5/2$) $= 0.25$

Total territoire 2 : $0.5$
:::
:::
